import React, { useState, useEffect, useCallback } from 'react';
import { m, AnimatePresence } from 'framer-motion';
import { ChevronLeft, ChevronRight } from 'lucide-react';

// Check if device is mobile
const isMobile = () => {
  return /Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(navigator.userAgent) || window.innerWidth < 768;
};

// Shuffle function for randomizing array order
const shuffleArray = (array) => {
  const shuffled = [...array];
  for (let i = shuffled.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [shuffled[i], shuffled[j]] = [shuffled[j], shuffled[i]];
  }
  return shuffled;
};

const Gallery = () => {
  const [selectedImage, setSelectedImage] = useState(null);
  const [loadedImages, setLoadedImages] = useState(new Set());
  const [images, setImages] = useState([]);
  const [loading, setLoading] = useState(true);
  const [currentMobileIndex, setCurrentMobileIndex] = useState(0);
  const mobile = isMobile();

  // Fetch images from static JSON file (generated by npm run sync-images)
  useEffect(() => {
    const fetchImages = async () => {
      try {
        const response = await fetch('/images-data.json');

        if (!response.ok) {
          throw new Error(`HTTP error! status: ${response.status}`);
        }

        const data = await response.json();

        if (data.images && data.images.length > 0) {
          setImages(shuffleArray(data.images));
        }

        // Minimum loading time to show the beautiful loading animation
        await new Promise(resolve => setTimeout(resolve, 1500));
        setLoading(false);
      } catch (error) {
        console.error('Error loading images:', error);
        console.log('Run "npm run sync-images" to generate the images data file');
        setLoading(false);
      }
    };

    fetchImages();
  }, []);

  const navigateImage = useCallback(
    (direction) => {
      if (!selectedImage) return;

      const currentIndex = images.findIndex(
        (img) => img.id === selectedImage.id
      );
      let newIndex;

      if (direction === 'next') {
        newIndex = currentIndex === images.length - 1 ? 0 : currentIndex + 1;
      } else {
        newIndex = currentIndex === 0 ? images.length - 1 : currentIndex - 1;
      }

      setSelectedImage(images[newIndex]);
    },
    [selectedImage, images]
  );

  // Handle keyboard navigation
  useEffect(() => {
    const handleKeyPress = (e) => {
      if (!selectedImage) return;

      switch (e.key) {
        case 'ArrowRight':
          navigateImage('next');
          break;
        case 'ArrowLeft':
          navigateImage('prev');
          break;
        case 'Escape':
          setSelectedImage(null);
          break;
        default:
          break;
      }
    };

    window.addEventListener('keydown', handleKeyPress);
    return () => window.removeEventListener('keydown', handleKeyPress);
  }, [selectedImage, navigateImage]);

  // Prevent context menu
  useEffect(() => {
    const preventDefault = (e) => e.preventDefault();
    document.addEventListener('contextmenu', preventDefault);
    return () => document.removeEventListener('contextmenu', preventDefault);
  }, []);

  const containerVariants = {
    hidden: { opacity: 0 },
    visible: {
      opacity: 1,
      transition: {
        staggerChildren: 0.15,
        delayChildren: 0.2,
      },
    },
  };

  const itemVariants = {
    hidden: {
      opacity: 0,
      y: 50,
      scale: 0.9,
    },
    visible: {
      opacity: 1,
      y: 0,
      scale: 1,
      transition: {
        duration: 0.6,
        ease: [0.25, 0.46, 0.45, 0.94],
      },
    },
  };

  const imageVariants = {
    loading: {
      opacity: 0,
      scale: isMobile() ? 0.95 : 0.6,
      filter: isMobile() ? 'blur(0px)' : 'blur(20px)',
      rotateY: isMobile() ? 0 : -25,
      y: isMobile() ? 10 : 30,
    },
    loaded: {
      opacity: 1,
      scale: 1,
      filter: 'blur(0px)',
      rotateY: 0,
      y: 0,
      transition: isMobile() ? {
        duration: 0.4,
        ease: 'easeOut'
      } : {
        duration: 1.2,
        ease: [0.19, 1.0, 0.22, 1.0],
        opacity: { duration: 0.6, delay: 0.2 },
        scale: { duration: 1.2, type: 'spring', stiffness: 80, damping: 12 },
        filter: { duration: 0.8, delay: 0.1 },
        rotateY: { duration: 1.0, ease: 'easeOut' },
        y: { duration: 1.0, ease: [0.19, 1.0, 0.22, 1.0] },
      }
    },
  };

  const handleImageLoad = (imageId) => {
    setLoadedImages(prev => new Set([...prev, imageId]));
  };

  // Mobile swipe handlers
  const handleMobileSwipe = (direction) => {
    if (direction === 'left' && currentMobileIndex < images.length - 1) {
      setCurrentMobileIndex(prev => prev + 1);
    } else if (direction === 'right' && currentMobileIndex > 0) {
      setCurrentMobileIndex(prev => prev - 1);
    }
  };

  return (
    <section id='gallery' className='pt-32 pb-20 bg-gray-50'>
      <div className='container mx-auto px-4'>
        <m.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.6 }}
          viewport={{ once: true }}
          className='text-center mb-12'
        >
          <h2 className='text-4xl font-bold mb-4 font-poppins tracking-tight text-gray-900'>
            My Work
          </h2>
          <p className='text-gray-600 max-w-2xl mx-auto font-inter'>
            A collection of my illustrations and digital artworks
          </p>
        </m.div>

        {loading && (
          <div className='text-center py-20'>
            <div className='max-w-md mx-auto'>
              {/* Modern loading bar container */}
              <div className='relative'>
                {/* Animated logo or icon */}
                <m.div
                  className='mb-8 flex justify-center'
                  animate={{
                    scale: [1, 1.1, 1],
                    rotate: [0, 5, -5, 0]
                  }}
                  transition={{
                    duration: 2,
                    repeat: Infinity,
                    ease: 'easeInOut'
                  }}
                >
                  <div className='w-16 h-16 rounded-full bg-gradient-to-r from-pink-500 to-purple-500 flex items-center justify-center shadow-lg'>
                    <svg className='w-8 h-8 text-white' fill='none' stroke='currentColor' viewBox='0 0 24 24'>
                      <path strokeLinecap='round' strokeLinejoin='round' strokeWidth={2} d='M4 16l4.586-4.586a2 2 0 012.828 0L16 16m-2-2l1.586-1.586a2 2 0 012.828 0L20 14m-6-6h.01M6 20h12a2 2 0 002-2V6a2 2 0 00-2-2H6a2 2 0 00-2 2v12a2 2 0 002 2z' />
                    </svg>
                  </div>
                </m.div>

                {/* Loading bar background */}
                <div className='w-full h-2 bg-gray-200 rounded-full overflow-hidden shadow-inner'>
                  {/* Animated loading bar */}
                  <m.div
                    className='h-full bg-gradient-to-r from-pink-500 via-purple-500 to-pink-500 rounded-full'
                    initial={{ x: '-100%' }}
                    animate={{ x: '100%' }}
                    transition={{
                      duration: 1.5,
                      repeat: Infinity,
                      ease: 'easeInOut'
                    }}
                    style={{
                      backgroundSize: '200% 100%',
                    }}
                  />
                </div>

                {/* Loading text */}
                <m.p
                  className='mt-6 text-gray-600 font-inter text-sm'
                  animate={{ opacity: [0.5, 1, 0.5] }}
                  transition={{
                    duration: 2,
                    repeat: Infinity,
                    ease: 'easeInOut'
                  }}
                >
                  Loading your beautiful artwork...
                </m.p>
              </div>
            </div>
          </div>
        )}

        {!loading && images.length === 0 && (
          <div className='text-center py-20'>
            <p className='text-gray-600'>No images found. Please upload images to your Cloudinary gallery.</p>
          </div>
        )}

        {!loading && images.length > 0 && (
          <>
            {/* Mobile Swiper View */}
            {mobile ? (
              <div className='relative max-w-md mx-auto'>
                <div className='relative aspect-[3/4] rounded-2xl overflow-hidden shadow-2xl'>
                  <m.img
                    key={currentMobileIndex}
                    src={images[currentMobileIndex].src}
                    alt={images[currentMobileIndex].title}
                    className='w-full h-full object-cover select-none'
                    drag='x'
                    dragConstraints={{ left: 0, right: 0 }}
                    dragElastic={0.1}
                    dragMomentum={false}
                    dragDirectionLock
                    onDragEnd={(e, { offset, velocity }) => {
                      // Very sensitive swipe detection
                      if (offset.x < -20) {
                        handleMobileSwipe('left');
                      } else if (offset.x > 20) {
                        handleMobileSwipe('right');
                      }
                    }}
                    onTap={() => setSelectedImage(images[currentMobileIndex])}
                  />

                  {/* Swipe indicator */}
                  <div className='absolute bottom-6 left-0 right-0 flex justify-center items-center gap-4 z-10'>
                    <m.button
                      onClick={(e) => { e.stopPropagation(); handleMobileSwipe('right'); }}
                      disabled={currentMobileIndex === 0}
                      className='bg-white/90 backdrop-blur-sm p-3 rounded-full shadow-lg disabled:opacity-30'
                      whileHover={{ scale: 1.1 }}
                      whileTap={{ scale: 0.9 }}
                    >
                      <ChevronLeft className='w-6 h-6 text-pink-500' />
                    </m.button>

                    <div className='bg-pink-500/80 backdrop-blur-sm w-2 h-2 rounded-full shadow-lg'>
                    </div>

                    <m.button
                      onClick={(e) => { e.stopPropagation(); handleMobileSwipe('left'); }}
                      disabled={currentMobileIndex === images.length - 1}
                      className='bg-white/90 backdrop-blur-sm p-3 rounded-full shadow-lg disabled:opacity-30'
                      whileHover={{ scale: 1.1 }}
                      whileTap={{ scale: 0.9 }}
                    >
                      <ChevronRight className='w-6 h-6 text-pink-500' />
                    </m.button>
                  </div>

                  {/* Drag hint */}
                  <m.div
                    className='absolute top-6 left-0 right-0 flex justify-center'
                    initial={{ opacity: 1 }}
                    animate={{ opacity: 0 }}
                    transition={{ delay: 2, duration: 1 }}
                  >
                    <div className='bg-white/90 backdrop-blur-sm px-4 py-2 rounded-full shadow-lg'>
                      <span className='text-xs text-gray-600'>← Swipe to browse →</span>
                    </div>
                  </m.div>
                </div>

                {/* Thumbnail strip */}
                <div className='flex gap-2 mt-6 overflow-x-auto pb-4 px-2 scrollbar-thin'>
                  {images.map((image, index) => (
                    <m.button
                      key={image.id}
                      onClick={() => setCurrentMobileIndex(index)}
                      className={`flex-shrink-0 w-16 h-16 rounded-lg overflow-hidden border-2 transition-all ${index === currentMobileIndex
                        ? 'border-pink-500 scale-110'
                        : 'border-transparent opacity-60'
                        }`}
                      whileTap={{ scale: 0.95 }}
                    >
                      <img
                        src={image.src}
                        alt={`Thumbnail ${index + 1}`}
                        className='w-full h-full object-cover'
                      />
                    </m.button>
                  ))}
                </div>
              </div>
            ) : (
              /* Desktop Grid View */
              <m.div
                variants={containerVariants}
                initial='hidden'
                whileInView='visible'
                viewport={{ once: true, margin: '-100px' }}
                className='grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8'
              >
                {images.map((image, index) => (
                  <m.div
                    key={image.id}
                    variants={!isMobile() ? itemVariants : undefined}
                    className='relative group cursor-pointer overflow-visible'
                    onClick={() => setSelectedImage(image)}
                    whileHover={!isMobile() ? {
                      scale: 1.05,
                      y: -12,
                      rotateZ: index % 2 === 0 ? 2 : -2,
                      transition: {
                        duration: 0.4,
                        ease: [0.34, 1.56, 0.64, 1]
                      }
                    } : undefined}
                    style={{ perspective: '1000px' }}
                  >
                    <div className='aspect-w-4 aspect-h-3 relative glass-card rounded-lg overflow-hidden shadow-lg'>
                      <m.img
                        src={image.src}
                        alt={image.title}
                        className='w-full h-64 object-cover pointer-events-none relative z-10 rounded-lg'
                        loading='lazy'
                        draggable='false'
                        onContextMenu={(e) => e.preventDefault()}
                        variants={imageVariants}
                        initial='loading'
                        animate={loadedImages.has(image.id) ? 'loaded' : 'loading'}
                        onLoad={() => handleImageLoad(image.id)}
                        style={{ transformStyle: 'preserve-3d' }}
                        whileHover={{
                          scale: 1.1,
                          filter: 'brightness(1.15) contrast(1.05)',
                          transition: { duration: 0.4 }
                        }}
                      />

                      {/* Enhanced Loading placeholder with shimmer */}
                      {!loadedImages.has(image.id) && (
                        <div className='absolute inset-0 bg-gradient-to-br from-gray-200 via-gray-100 to-gray-300 rounded-lg z-0 overflow-hidden'>
                          <m.div
                            className='absolute inset-0 bg-gradient-to-r from-transparent via-white/40 to-transparent'
                            animate={{
                              x: ['-100%', '100%'],
                            }}
                            transition={{
                              duration: 1.5,
                              repeat: Infinity,
                              ease: 'linear',
                            }}
                          />
                        </div>
                      )}

                      {/* Reveal overlay effect */}
                      {loadedImages.has(image.id) && (
                        <m.div
                          className='absolute inset-0 bg-gradient-to-r from-pink-500/0 via-pink-400/30 to-pink-500/0 z-30 pointer-events-none'
                          initial={{ x: '-100%', opacity: 1 }}
                          animate={{ x: '100%', opacity: 0 }}
                          transition={{
                            x: { duration: 1, ease: 'easeInOut' },
                            opacity: { duration: 0.8, delay: 0.2 },
                          }}
                        />
                      )}

                      {/* Simple Overlay */}
                      <m.div
                        className='absolute inset-0 flex items-end justify-center pb-6 z-20 rounded-lg overflow-hidden'
                      >
                        {/* Minimal light pink gradient background on hover */}
                        <m.div
                          className='absolute inset-0 bg-gradient-to-t from-pink-100/30 to-transparent'
                          initial={{ opacity: 0, y: 20 }}
                          whileHover={{ opacity: 1, y: 0 }}
                          transition={{ duration: 0.3 }}
                        />

                        {/* Text with simple animation */}
                        <m.p
                          className='text-gray-800 text-lg font-semibold relative z-30'
                          initial={{ opacity: 0, y: 10 }}
                          whileHover={{
                            opacity: 1,
                            y: 0,
                            transition: {
                              duration: 0.3,
                            }
                          }}
                        >
                          Click to view
                        </m.p>
                      </m.div>
                    </div>
                  </m.div>
                ))}
              </m.div>
            )}
          </>
        )}

        {/* Image Modal */}
        <AnimatePresence>
          {selectedImage && (
            <m.div
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              exit={{ opacity: 0 }}
              className='fixed inset-0 bg-black bg-opacity-90 z-50 p-4 flex items-center justify-center'
              onClick={() => setSelectedImage(null)}
            >
              <button
                className='absolute top-4 right-4 text-white text-4xl hover:text-pink-500 transition-colors'
                onClick={(e) => {
                  e.stopPropagation();
                  setSelectedImage(null);
                }}
              >
                ×
              </button>

              {/* Navigation buttons */}
              <button
                className='absolute left-4 top-1/2 -translate-y-1/2 text-white hover:text-pink-500 transition-colors p-2'
                onClick={(e) => {
                  e.stopPropagation();
                  navigateImage('prev');
                }}
              >
                <ChevronLeft size={40} />
              </button>

              <button
                className='absolute right-4 top-1/2 -translate-y-1/2 text-white hover:text-pink-500 transition-colors p-2'
                onClick={(e) => {
                  e.stopPropagation();
                  navigateImage('next');
                }}
              >
                <ChevronRight size={40} />
              </button>

              <m.img
                src={selectedImage.src}
                alt={selectedImage.title}
                className='max-h-[90vh] max-w-[90vw] object-contain rounded-lg pointer-events-none'
                draggable='false'
                onContextMenu={(e) => e.preventDefault()}
                initial={{ opacity: 0, scale: 0.9 }}
                animate={{ opacity: 1, scale: 1 }}
                transition={{ duration: 0.3, ease: 'easeOut' }}
              />

              {/* Image counter */}
              <div className='absolute bottom-4 left-1/2 -translate-x-1/2 text-white bg-black bg-opacity-50 px-4 py-2 rounded-full'>
                {images.findIndex((img) => img.id === selectedImage.id) + 1} /{' '}
                {images.length}
              </div>
            </m.div>
          )}
        </AnimatePresence>
      </div>
    </section>
  );
};

export default Gallery;
